mv af.po_ af.po
mv agr.po_ agr.po
mv am.po_ am.po
mv ar.po_ ar.po
mv ayc.po_ ayc.po
mv bg.po_ bg.po
mv bi.po_ bi.po
mv bn.po_ bn.po
mv br.po_ br.po
mv ca.po_ ca.po
mv cs.po_ cs.po
mv da.po_ da.po
mv de.po_ de.po
mv dz.po_ dz.po
mv el.po_ el.po
mv en_GB.po_ en_GB.po
mv en.po_ en.po
mv es.po_ es.po
mv fa.po_ fa.po
mv ff.po_ ff.po
mv fil.po_ fil.po
mv fi.po_ fi.po
mv fr.po_ fr.po
mv gn.po_ gn.po
mv ha.po_ ha.po
mv he.po_ he.po
mv hi.po_ hi.po
mv ht.po_ ht.po
mv hu.po_ hu.po
mv hus.po_ hus.po
mv hy.po_ hy.po
mv ibo.po_ ibo.po
mv id.po_ id.po
mv is.po_ is.po
mv it.po_ it.po
mv ja.po_ ja.po
mv km.po_ km.po
mv ko.po_ ko.po
mv kos.po_ kos.po
mv mg.po_ mg.po
mv mi.po_ mi.po
mv mk.po_ mk.po
mv ml.po_ ml.po
mv mn.po_ mn.po
mv mr.po_ mr.po
mv ms.po_ ms.po
mv mvo.po_ mvo.po
mv nb.po_ nb.po
mv ne.po_ ne.po
mv nl.po_ nl.po
mv pa.po_ pa.po
mv pap.po_ pap.po
mv pbs.po_ pbs.po
mv pl.po_ pl.po
mv pt.po_ pt.po
mv quz.po_ quz.po
mv ro.po_ ro.po
mv ru.po_ ru.po
mv rw.po_ rw.po
mv sd.po_ sd.po
mv si.po_ si.po
mv sk.po_ sk.po
mv sl.po_ sl.po
mv sq.po_ sq.po
mv sv.po_ sv.po
mv sw.po_ sw.po
mv ta.po_ ta.po
mv te.po_ te.po
mv th.po_ th.po
mv tr.po_ tr.po
mv tvl.po_ tvl.po
mv tzo.po_ tzo.po
mv ug.po_ ug.po
mv ur.po_ ur.po
mv vi.po_ vi.po
mv wa.po_ wa.po
mv yo.po_ yo.po
mv zh_CN.po_ zh_CN.po
mv zh_TW.po_ zh_TW.po
