python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot af.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot agr.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot am.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot ar.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot ayc.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot bg.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot bi.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot bn.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot br.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot ca.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot cs.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot da.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot de.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot dz.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot el.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot en_GB.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot en.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot es.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot fa.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot ff.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot fil.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot fi.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot fr.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot gn.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot ha.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot he.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot hi.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot ht.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot hu.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot hus.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot hy.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot ibo.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot id.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot is.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot it.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot ja.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot km.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot ko.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot kos.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot mg.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot mi.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot mk.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot ml.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot mn.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot mr.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot ms.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot mvo.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot nb.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot ne.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot nl.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot pa.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot pap.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot pbs.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot pl.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot pt.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot quz.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot ro.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot ru.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot rw.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot sd.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot si.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot sk.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot sl.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot sq.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot sv.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot sw.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot ta.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot te.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot th.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot tr.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot tvl.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot tzo.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot ug.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot ur.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot vi.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot wa.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot yo.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot zh_CN.po
python /home/walter/Desktop/po-to-ini/pot2po.py TurtleBlocksJS.pot zh_TW.po
